//////////Transaction Details//////
CREATE TABLE TRANSACTION_DETAILS
(
TRANSACTION_ID INT(10) ,
TRANSACTION_DESCRIPTION VARCHAR(20),
TRANSACTION_TYPE VARCHAR(10),
TRANSACTION_AMOUNT BIGINT(20),
PRIMARY KEY (TRANSACTION_ID)
);
/////User Details //////
create table UserDetails(
accountNumber BIGINT(16),
accountType VARCHAR(20),
accountHolderName VARCHAR(20),
accountBalance BIGINT(20),PRIMARY KEY(accountNumber)
);
/////////Home Loan Details//////
CREATE TABLE homeloandetails
(
HOME_LOAN_ID varchar(16),
HOME_LOAN_ACCOUNT_NUMBER BIGINT(16),
LOAN_AMOUNT BIGINT(16),
LOAN_APPLY_DATE DATE,
LOAN_DURATION INT(2),
ANNUAL_INCOME BIGINT(16),
COMP_NAME varchar(30),
DESIGNATION varchar(30),
TOTAL_EXP INT(2),
EXP_CURRENT_COMP INT(2),
PRIMARY KEY (HOME_LOAN_ID));


////education loan//////////
CREATE TABLE educationloandetails
(
EDUCATION_LOAN_ID varchar(16),
EDU_LOAN_ACCOUNT_NUMBER BIGINT(16),
EDU_LOAN_AMOUNT BIGINT(16),
EDU_LOAN_APPLY_DATE DATE,
EDU_LOAN_DURATION INT(2),
FATHER_ANNUAL_INCOME BIGINT(16),
FATHER_NAME varchar(30),
COURSE_FEE BIGINT(16),
COURSE_NAME varchar(30),
ID_CARD_NUMBER BIGINT(16),
ACCOUNT_NUMBER BIGINT(16),
PRIMARY KEY (EDUCATION_LOAN_ID)); 

